use actix_web::{web, Scope};
use crate::security::permission::RequirePermission;

pub fn api_scope() -> Scope {
    web::scope("")
        .route("/healthz", web::get().to(crate::http::handlers::health::healthz))
    // OR Cases (aligned with root.sql)
    .service(web::resource("/api/v1/or-cssd/or-cases")
      .wrap(RequirePermission::new(crate::security::policy::perm::OR_CASE_LIST))
      .route(web::get().to(crate::http::handlers::or_cases::list_or_cases))
      .route(web::post().to(crate::http::handlers::or_cases::create_or_case)))
    .service(web::resource("/api/v1/or-cssd/or-cases/{id}")
      .wrap(RequirePermission::new(crate::security::policy::perm::OR_CASE_GET))
      .route(web::get().to(crate::http::handlers::or_cases::get_or_case))
      .route(web::put().to(crate::http::handlers::or_cases::update_or_case))
      .route(web::delete().to(crate::http::handlers::or_cases::delete_or_case)))
    .service(web::resource("/api/v1/or-cssd/or-cases/stats")
      .wrap(RequirePermission::new(crate::security::policy::perm::OR_CASE_VIEW))
      .route(web::get().to(crate::http::handlers::or_cases::get_or_case_stats)))
    .service(web::resource("/api/v1/or-cssd/or-cases/{id}/checklists")
      .wrap(RequirePermission::new(crate::security::policy::perm::OR_CHECKLIST_MANAGE))
      .route(web::get().to(crate::http::handlers::or_cases::get_or_case_checklists))
      .route(web::post().to(crate::http::handlers::or_cases::create_or_checklist)))
    .service(web::resource("/api/v1/or-cssd/checklists/{id}")
      .wrap(RequirePermission::new(crate::security::policy::perm::OR_CHECKLIST_MANAGE))
      .route(web::put().to(crate::http::handlers::or_cases::update_or_checklist)))
    // CSSD Trays (aligned with root.sql)
    .service(web::resource("/api/v1/or-cssd/cssd/trays")
      .wrap(RequirePermission::new(crate::security::policy::perm::CSSD_TRAY_LIST))
      .route(web::get().to(crate::http::handlers::cssd_trays::list_cssd_trays))
      .route(web::post().to(crate::http::handlers::cssd_trays::create_cssd_tray)))
    .service(web::resource("/api/v1/or-cssd/cssd/trays/{id}")
      .wrap(RequirePermission::new(crate::security::policy::perm::CSSD_TRAY_GET))
      .route(web::get().to(crate::http::handlers::cssd_trays::get_cssd_tray))
      .route(web::put().to(crate::http::handlers::cssd_trays::update_cssd_tray))
      .route(web::delete().to(crate::http::handlers::cssd_trays::delete_cssd_tray)))
    .service(web::resource("/api/v1/or-cssd/cssd/trays/{id}/items")
      .wrap(RequirePermission::new(crate::security::policy::perm::CSSD_TRAY_ITEM_MANAGE))
      .route(web::get().to(crate::http::handlers::cssd_trays::get_cssd_tray_items))
      .route(web::post().to(crate::http::handlers::cssd_trays::create_cssd_tray_item)))
    // CSSD Sterilization Lots (aligned with root.sql)
    .service(web::resource("/api/v1/or-cssd/cssd/sterilization-lots")
      .wrap(RequirePermission::new(crate::security::policy::perm::CSSD_LOT_LIST))
      .route(web::get().to(crate::http::handlers::cssd_trays::list_cssd_sterilization_lots))
      .route(web::post().to(crate::http::handlers::cssd_trays::create_cssd_sterilization_lot)))
    .service(web::resource("/api/v1/or-cssd/cssd/sterilization-lots/{id}")
      .wrap(RequirePermission::new(crate::security::policy::perm::CSSD_LOT_GET))
      .route(web::get().to(crate::http::handlers::cssd_trays::get_cssd_sterilization_lot))
      .route(web::put().to(crate::http::handlers::cssd_trays::update_cssd_sterilization_lot)))
    .service(web::resource("/api/v1/or-cssd/cssd/sterilization-lots/{id}/items")
      .wrap(RequirePermission::new(crate::security::policy::perm::CSSD_LOT_ITEM_MANAGE))
      .route(web::get().to(crate::http::handlers::cssd_trays::get_cssd_lot_items))
      .route(web::post().to(crate::http::handlers::cssd_trays::create_cssd_lot_item)))
    .service(web::resource("/api/v1/or-cssd/cssd/expired-items")
      .wrap(RequirePermission::new(crate::security::policy::perm::CSSD_VIEW))
      .route(web::get().to(crate::http::handlers::cssd_trays::get_expired_cssd_items)))
}
