# IAM Service Production Configuration
server:
  host: "0.0.0.0"
  port: 8001

database:
  url: "postgresql://postgres:${DB_PASSWORD}@postgres:5432/his_iam"
  max_connections: 20

redis:
  url: "redis://redis:6379"

kafka:
  bootstrap_servers: "kafka:9092"
  group_id: "iam-service"

auth:
  keycloak:
    url: "https://keycloak.his.local"
    realm: "his"
    client_id: "iam-service"

telemetry:
  jaeger_endpoint: "http://jaeger:14268/api/traces"
  service_name: "iam-service"
