CREATE TABLE IF NOT EXISTS inv_items (
  id UUID PRIMARY KEY,
  code VARCHAR(64) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  uom VARCHAR(32) NOT NULL DEFAULT 'EA',
  is_med BOOLEAN NOT NULL DEFAULT FALSE,
  is_consumable BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
