apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-data-service
  namespace: his
spec:
  replicas: 2
  selector:
    matchLabels:
      app: master-data-service
  template:
    metadata:
      labels:
        app: master-data-service
    spec:
      containers:
      - name: master-data-service
        image: his/master-data-service:latest
        ports:
        - containerPort: 8002
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: master-secrets
              key: database-url
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"

---
apiVersion: v1
kind: Service
metadata:
  name: master-data-service
  namespace: his
spec:
  selector:
    app: master-data-service
  ports:
  - port: 8002
    targetPort: 8002
  type: ClusterIP
