CREATE TABLE IF NOT EXISTS dispenses (
  id UUID PRIMARY KEY,
  prescription_id UUID NOT NULL REFERENCES prescriptions(id) ON DELETE CASCADE,
  disp_no VARCHAR(64) UNIQUE NOT NULL,
  dispensed_by VARCHAR(64),
  status VARCHAR(16) NOT NULL DEFAULT 'NEW', -- NEW/COMPLETED/CANCELLED
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
