# Billing Service Configuration
server:
  host: "0.0.0.0"
  port: 8008

database:
  url: "postgresql://postgres:postgres@localhost:5432/his_billing"
  max_connections: 10

redis:
  url: "redis://localhost:6379"

kafka:
  bootstrap_servers: "localhost:9092"
  group_id: "billing-service"

telemetry:
  jaeger_endpoint: "http://localhost:14268/api/traces"
  service_name: "billing-service"
