# IAM Service Configuration
server:
  host: "0.0.0.0"
  port: 8001

database:
  url: "postgresql://postgres:postgres@localhost:5432/his_iam"
  max_connections: 10

redis:
  url: "redis://localhost:6379"

kafka:
  bootstrap_servers: "localhost:9092"
  group_id: "iam-service"

auth:
  keycloak:
    url: "http://localhost:8080"
    realm: "his"
    client_id: "iam-service"
    client_secret: "your-client-secret"

telemetry:
  jaeger_endpoint: "http://localhost:14268/api/traces"
  service_name: "iam-service"
