# Insurance Service Configuration
server:
  host: "0.0.0.0"
  port: 8009

database:
  url: "postgresql://postgres:postgres@localhost:5432/his_insurance"
  max_connections: 10

redis:
  url: "redis://localhost:6379"

kafka:
  bootstrap_servers: "localhost:9092"
  group_id: "insurance-service"

external_apis:
  bhyt:
    url: "https://api.bhyt.gov.vn"
    timeout: 30
  private_insurer:
    url: "https://api.private-insurer.com"
    timeout: 30

telemetry:
  jaeger_endpoint: "http://localhost:14268/api/traces"
  service_name: "insurance-service"
