# Inventory Service Configuration
server:
  host: "0.0.0.0"
  port: 8007

database:
  url: "postgresql://postgres:postgres@localhost:5432/his_inventory"
  max_connections: 10

redis:
  url: "redis://localhost:6379"

kafka:
  bootstrap_servers: "localhost:9092"
  group_id: "inventory-service"

telemetry:
  jaeger_endpoint: "http://localhost:14268/api/traces"
  service_name: "inventory-service"
