# Notification Service Configuration
server:
  host: "0.0.0.0"
  port: 8012

database:
  url: "postgresql://postgres:postgres@localhost:5432/his_notify"
  max_connections: 10

redis:
  url: "redis://localhost:6379"

kafka:
  bootstrap_servers: "localhost:9092"
  group_id: "notify-service"

channels:
  email:
    smtp_host: "localhost"
    smtp_port: 587
    smtp_username: "noreply@hospital.com"
    smtp_password: "password"
  sms:
    provider: "twilio"
    account_sid: "your-account-sid"
    auth_token: "your-auth-token"
  push:
    fcm_server_key: "your-fcm-server-key"

telemetry:
  jaeger_endpoint: "http://localhost:14268/api/traces"
  service_name: "notify-service"
