# OR-CSSD Service Configuration
server:
  host: "0.0.0.0"
  port: 8010

database:
  url: "postgresql://postgres:postgres@localhost:5432/his_or_cssd"
  max_connections: 10

redis:
  url: "redis://localhost:6379"

kafka:
  bootstrap_servers: "localhost:9092"
  group_id: "or-cssd-service"

telemetry:
  jaeger_endpoint: "http://localhost:14268/api/traces"
  service_name: "or-cssd-service"
